// This file is auto-generated by @hey-api/openapi-ts

export const UserSchema = {
    type: 'object',
    properties: {
        pesel: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        lastName: {
            type: 'string'
        },
        readDateTime: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;