// This file is auto-generated by @hey-api/openapi-ts

export const UserRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        lastName: {
            type: 'string'
        },
        cardId: {
            type: 'string'
        }
    }
} as const;

export const UserDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int32'
        },
        name: {
            type: 'string'
        },
        lastName: {
            type: 'string'
        },
        cardId: {
            type: 'string'
        },
        readDateTime: {
            type: 'string'
        }
    }
} as const;