// This file is auto-generated by @hey-api/openapi-ts

export type UserRequest = {
    name?: string;
    lastName?: string;
    cardId?: string;
};

export type UserDto = {
    id?: number;
    name?: string;
    lastName?: string;
    cardId?: string;
    readDateTime?: string;
};

export type DeleteUserData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type DeleteUserResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateUserData = {
    body: UserRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type UpdateUserResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type GetUsersResponses = {
    /**
     * OK
     */
    200: Array<UserDto>;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type AddUserData = {
    body: UserRequest;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type AddUserResponses = {
    /**
     * Created
     */
    201: UserDto;
};

export type AddUserResponse = AddUserResponses[keyof AddUserResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};