// This file is auto-generated by @hey-api/openapi-ts

export type User = {
    pesel?: string;
    name?: string;
    lastName?: string;
    readDateTime?: string;
};

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type GetUsersResponses = {
    /**
     * OK
     */
    200: Array<User>;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8888' | (string & {});
};